### ISSUE TITLE
Problem with eestats2 for longer reads

### ISSUE THREAD

**Issue by anamailyan** [torognes/vsearch#336] opened 2018-09-24 00:53 UTC
When running vsearch and usearch with --eestats2 option on same file I get very different numbers in output  for reads longer than 300. It appears vsearch numbers are wrong unless I am missing something.
`$ vsearch --fastq_eestats2 ../vsearch-output/all_samples_concatenated.fastq --output vsearch.eestats2.txt `
```
1055197 reads, max len 486, avg 257.4

Length         MaxEE 0.50         MaxEE 1.00         MaxEE 2.00
------   ----------------   ----------------   ----------------
    50    1029866( 97.6%)    1034447( 98.0%)    1054460( 99.9%)
   100     996751( 94.5%)    1028386( 97.5%)    1052579( 99.8%)
   150     943091( 89.4%)    1000181( 94.8%)    1045517( 99.1%)
   200     895330( 84.8%)     959869( 91.0%)    1023148( 97.0%)
   250     803383( 76.1%)     876470( 83.1%)     946161( 89.7%)
   300     793848( 75.2%)     869432( 82.4%)     943481( 89.4%)
   350     793163( 75.2%)     868743( 82.3%)     942825( 89.4%)
   400     792870( 75.1%)     868405( 82.3%)     942507( 89.3%)
   450     771463( 73.1%)     845776( 80.2%)     919396( 87.1%)

```
`$ usearch -fastq_eestats2 ../vsearch-output/all_samples_concatenated.fastq -output usearch.eestats2.txt`

```
1055197 reads, max len 486, avg 257.4

Length         MaxEE 0.50         MaxEE 1.00         MaxEE 2.00
------   ----------------   ----------------   ----------------
    50    1029866( 97.6%)    1034447( 98.0%)    1054460( 99.9%)
   100     996751( 94.5%)    1028386( 97.5%)    1052579( 99.8%)
   150     943091( 89.4%)    1000181( 94.8%)    1045517( 99.1%)
   200     895330( 84.8%)     959869( 91.0%)    1023148( 97.0%)
   250     803383( 76.1%)     876470( 83.1%)     946161( 89.7%)
   300       2945(  0.3%)       4238(  0.4%)       5508(  0.5%)
   350       1989(  0.2%)       3154(  0.3%)       4372(  0.4%)
   400        443(  0.0%)        832(  0.1%)       1310(  0.1%)
   450          5(  0.0%)         21(  0.0%)         46(  0.0%)
```

**Comment by torognes** [comment] 2018-09-26 15:06
Thanks for reporting this issue. It seems like something happens when the length goes from 250 to 300. For lengths up to 250 the numbers look identical. It is hard to know which program is correct here without more data. Would it be possible for you to send me or point to the dataset you have used?

**Comment by anamailyan** [comment] 2018-09-26 15:49
I tried to upload file when I was submitting the issue, but file was too
big.
I'll try to attach to this email. I did check numbers. It seems vsearch
numbers are not correct for longer reads.
Thank you for looking into this.
 all_samples_concatenated.fastq
<https://drive.google.com/file/d/1-t26TzmGHmyHxwu_avXfP9hOHgcJZPzK/view?usp=drive_web>

**Comment by torognes** [comment] 2018-09-26 15:53
Thanks. I found the error in the code now. It's a bug and I cannot understand why I wrote the code that way. I'll release a fix very soon.

**Comment by torognes** [comment] 2018-09-26 17:02
The problem is fixed in vsearch version 2.8.5 just released.

**Comment by torognes** [comment] 2018-09-26 17:07
The bug caused the values computed with fastq_eestats2 for large lengths to be much too high when the input sequences had varying lengths.

**Comment by frederic-mahe** [comment] 2018-09-26 17:42
I've been trying to make a toy example that can trigger the bug, but without success so far. 
```cpp
      for (int x = 0; x < len_steps; x++)
        {
          uint64_t len_cutoff = opt_length_cutoffs_shortest + x * opt_length_cutoffs_increment;
          if (len < len_cutoff)
            for (int y = 0; y < opt_ee_cutoffs_count; y++)
              if (ee <= opt_ee_cutoffs_values[y])
                count_table[x * opt_ee_cutoffs_count + y]++;
        }
```
Is the bug triggered by mixed sequence lengths?

**Comment by frederic-mahe** [comment] 2018-09-26 17:45
In fact, I cannot even reproduce the bug when using the dataset posted by anamailyan with vsearch v2.8.4.

**Comment by torognes** [comment] 2018-09-26 17:45
Yes, the sequences must have different lengths. Try with one short sequence and one long sequence.

**Comment by anamailyan** [comment] 2018-09-26 19:36
Thank you! I'll give it  a try.

**Comment by torognes** [comment] 2018-09-27 10:10
I'll try to make a small dataset to reproduce it, but it was more difficult than expected.

**Comment by torognes** [comment] 2018-09-27 10:27
Ok, here is a minimalistic dataset, `toy.fastq`:

```
@1
AA
+
AA
@2
A
+
A
```

If you run vsearch 2.8.4 or earlier you'll get these results:

```sh
$ vsearch --fastq_eestats2 toy.fastq --output - --length_cutoffs 1,2,1
vsearch v2.8.4_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading FASTQ file 100%  
2 reads, max len 2, avg 1.5

Length         MaxEE 0.50         MaxEE 1.00         MaxEE 2.00
------   ----------------   ----------------   ----------------
     1          2(100.0%)          2(100.0%)          2(100.0%)
     2          2(100.0%)          2(100.0%)          2(100.0%)
```

If you run vsearch 2.8.5, you'll get this:

```sh
$ vsearch --fastq_eestats2 toy.fastq --output - --length_cutoffs 1,2,1
vsearch v2.8.5_macos_x86_64, 16.0GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading FASTQ file 100%  
2 reads, max len 2, avg 1.5

Length         MaxEE 0.50         MaxEE 1.00         MaxEE 2.00
------   ----------------   ----------------   ----------------
     1          2(100.0%)          2(100.0%)          2(100.0%)
     2          1( 50.0%)          1( 50.0%)          1( 50.0%)
```

What the old version did was kind of extending all sequences with perfect quality bases up to the length of the longest previously seen sequence. If all sequences are equally long, the results are the same. With varying length sequences, the old results will be wrong, starting from the length of the shortest sequence.

**Comment by frederic-mahe** [comment] 2018-10-02 09:59
Perfect @torognes ! I've just added a test for that issue (https://github.com/frederic-mahe/vsearch-tests/commit/c71a498728b15b34263b475037bd19e065b0803a).

**Closed** 2018-10-02 10:00 UTC
Labels: bug
