### ISSUE TITLE
vsearch 2.7.0 breaks identify_chimeric_seqs.py (qiime 1.9.1)

### ISSUE THREAD

**Issue by granek** [torognes/vsearch#301] opened 2018-04-05 05:10 UTC
Upgrading from vsearch 2.6.0 to 2.7.0 seems to have broken "identify_chimeric_seqs.py --chimera_detection_method usearch61" (qiime 1.9.1) for me when using vsearch as a drop in replacement for usearch61.

I have a script that worked a few months ago but is now failing at identify_chimeric_seqs.py.  I have updated software since then, but was able to isolate the problem to vsearch because pinning vsearch to 2.6.0 (with nothing else changed) fixes it.

I can put together an MWE and docker images that replicate the problem if you need this.

**Comment by torognes** [comment] 2018-04-05 11:40
Thank you for reporting this problem. Do you get any output or error messages when running it with vsearch 2.7.0 that you could provide in order to help me narrow down the problem?

**Comment by torognes** [comment] 2018-04-05 12:09
I have run uchime_denovo and uchime_ref using vsearch version 2.6.0 and 2.7.0 on a few test sets and default parameters but I always get exactly the same results. I think I need some more details to figure out what the problem is.

**Comment by granek** [comment] 2018-04-05 19:40
Sorry, I was so excited to finally figure out the problem that I forgot to give the error.  I'll work on putting together the MWE in case this isn't sufficient.

```
Traceback (most recent call last):
  File "/opt/conda/bin/identify_chimeric_seqs.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'identify_chimeric_seqs.py')
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/identify_chimeric_seqs.py", line 354, in <module>
    main()
  File "/opt/conda/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/identify_chimeric_seqs.py", line 350, in main
    threads=threads)
  File "/opt/conda/lib/python2.7/site-packages/qiime/identify_chimeric_seqs.py", line 774, in usearch61_chimera_check
    log_lines, verbose, threads)
  File "/opt/conda/lib/python2.7/site-packages/qiime/identify_chimeric_seqs.py", line 933, in identify_chimeras_usearch61
    de_novo_chimeras = get_chimera_clusters(denovo_uchime_fp)
  File "/opt/conda/lib/python2.7/site-packages/qiime/identify_chimeric_seqs.py", line 1100, in get_chimera_clusters
    curr_line[seq_id_ix].split('centroid=')[1].split(';')[0])
IndexError: list index out of range
```

**Comment by torognes** [comment] 2018-04-11 15:14
I think I have found the problem and fixed it in the latest commit. Would it be possible for you, @granek , to test if it solves the issue? You'll then need to clone or download the repo and compile the code as it is in the released version.

**Comment by torognes** [comment] 2018-04-20 13:28
Fixed in version 2.7.2 just released.

**Closed by torognes** 2018-04-20 13:28 UTC
Labels: bug

**Comment by granek** [comment] 2018-04-27 21:41
I just confirmed that version 2.7.2 fixes the problem that I was having.  Thanks for the quick response, I apologize for not checking earlier.

FWIW, version 2.7.2 seems to think it is 2.8.0:
```  
$ cd /tmp && \
    wget https://github.com/torognes/vsearch/archive/v2.7.2.tar.gz && \
    tar xzf v2.7.2.tar.gz && \
    cd vsearch-2.7.2 && \
    ./autogen.sh && \
    ./configure && \
    make
#  . . . skipping output

$ bin/vsearch --version
vsearch v2.8.0_linux_x86_64, 55.0GB RAM, 16 cores
```

**Comment by torognes** [comment] 2018-04-30 10:04
@granek Thanks for checking it out - I'm glad it solved the problem.

I messed up a few things when naming release/tag 2.6.1 and 2.7.2 and messed up again when I tried to fix it. I have removed those two releases now to avoid confusion.
