### ISSUE TITLE
vsearch --uchime_ref gzip not supported

### ISSUE THREAD

**Issue by davidvilanova** [torognes/vsearch#369] opened 2019-04-26 10:39 UTC
Hello,
Would it be possible to support gzip files when using uchime_ref ???

> vsearch --uchime_ref file.fa.gz --db database.fa 

`Fatal error: Files compressed with gzip are not supported.
`
Thanks

**Comment by torognes** [comment] 2019-04-26 11:18
VSEARCH should support compressed files for this command, both for the input file and the database. But it requires that it was compiled with that support and that the necessary libraries are available.

Did you compile it yourself or did you use one of the precompiled binaries of a release?

Which VSEARCH version and platform (Linux/Mac/Win etc) are you using?

**Comment by frederic-mahe** [comment] 2019-04-26 11:46
@davidvilanova since vsearch can read fom `stdin`, you can do:
```
vsearch --uchime_ref <(zcat file.fa.gz) --db database.fa
```
or `gunzip -c file.fa.gz` if zcat is not installed.

**Comment by davidvilanova** [comment] 2019-04-26 12:11
Thanks, i use vsearch v2.13.0 on linux 
I used the zcat alternative.

**Comment by davidvilanova** [comment] 2019-04-26 12:24
Realized it is the conda version that has been compiled without gzip support.

**Comment by colinbrislawn** [comment] 2019-04-26 15:29
The version on conda _should_ included gzip support, as zlib is included in both the build and run step.

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/vsearch/meta.yaml#L25

Is anyone more familiar with conda recipes?

**Comment by colinbrislawn** [comment] 2019-05-01 19:20
Can we reopen this issue? I've just confirmed that vsearch v2.13.1 on conda does not support gzip.

I'm not sure if I should post this issue on bioconda or in this repo. Feedback welcome!

**Comment by torognes** [comment] 2019-05-02 11:37
In order for VSEARCH to be able to use (de)compression the following is needed:

- The `--disable-zlib` and/or the `--disable-bzip2` options must NOT be specified to configure.
- The `zlib.h` and/or `bzlib.h` header files need to be available when running configure and make.
- The `zlib` and/or the `libbz2` dynamic libraries must be available in one of the default library locations.

On Linux the libraries are called `libz.so` and `libbz2.so` and are usually found in `/usr/lib` or `/lib`.

On macOS the libraries are called `libz.dylib` and `libbz2.dylib` and are usually found in `/usr/lib`.

On Windows the libraries are called `zlib1.dll` and `libbz2.dll`.

VSEARCH will try to load these dynamic libraries when starting, but will not exit if they are not available. Currently, it does not tell if they are available or not. Perhaps some information should be added to the `--version` command to indicate the status.

**Comment by colinbrislawn** [comment] 2019-05-25 19:26
We fixed it. The version of vsearch on conda supports gzip and bzip again. 
https://github.com/bioconda/bioconda-recipes/pull/15007 

I think we can safely close this issue. :shipit:

**Comment by frederic-mahe** [comment] 2019-05-26 13:39
Thanks @colinbrislawn

**Closed by frederic-mahe** 2019-05-26 13:39 UTC
Labels: question
